# Generated by Django 3.0.5 on 2022-01-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220108_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
