# Generated by Django 3.0.5 on 2022-01-11 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twit', '0004_auto_20220111_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReTiwt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('twit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twit.Twit')),
            ],
            options={
                'verbose_name': 'ReTwit',
                'verbose_name_plural': 'ReTwits',
            },
        ),
    ]
