# Generated by Django 3.0.5 on 2022-01-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0006_auto_20220111_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='retwit',
            name='retwit',
            field=models.BooleanField(default=True),
        ),
    ]
