# Generated by Django 3.0.5 on 2022-01-12 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0007_retwit_retwit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retwit',
            options={'ordering': ['-created_at'], 'verbose_name': 'ReTwit', 'verbose_name_plural': 'ReTwits'},
        ),
        migrations.AlterModelOptions(
            name='twit',
            options={'ordering': ['created_at'], 'verbose_name': 'Twit', 'verbose_name_plural': 'Twits'},
        ),
    ]
